### ISSUE TITLE
Python code to automate the submission.

### ISSUE THREAD

**Issue by rkgeekoftheweek** [watashi-wa-sidhant/Automating-codechef-submissions#1]
@watashi-wa-sidhant , 
I can write code for this problem in python.
1. Assign this issue to me.
2. Add hacktoberfest tag to this issue.

**Comment by rkgeekoftheweek** [comment]
@watashi-wa-sidhant , #3 
please check my pull request and close this issue.

**Comment by rkgeekoftheweek** [comment]
code can be further enhanced 
1. adding exception handling for scenarios failed login and failed submission.
2. U can add code to select  programming language to submit code  
3. Once code is submitted , logout from site.

**Comment by watashi-wa-sidhant** [comment]
Thanks for that info @rkgeekoftheweek
